/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package brood.stock.management.system;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author ADMIN
 */
public class Invoice1 extends javax.swing.JFrame {
 Connection con=null;
    PreparedStatement pst=null;
    ResultSet rs =null;
    Statement st=null;
    /**
     * Creates new form Invoice1
     */
    public Invoice1() {
        initComponents();
        IDisplay();
        InvoiceCount();
        
       
          jTextArea1.setText("====================================================================="+"\n"+
                
                "\t"+"Company name: MBR INVESTMENT LIMITED"+"\n"+"\t"+"Contact No:0789453423"+"\n"+"\t"+
                "Address: Wakiso"+"\n"+"======================================================"+"\n");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    @SuppressWarnings("unchecked")
            
    int Invoice, CId;
    String customerdetails, date, time;
    int quantity;
    int price;
     public void print(){
         
       Invoice =Integer.valueOf(invoice.getText());
        quantity=Integer.valueOf(quantitytbl.getText());
        date=jdate.getText();
        time=jtime.getText();
        customerdetails=customer.getText();
         
         price=quantity * 320;
        jTextArea1.setText(jTextArea1.getText()+"\nInvoiceId:  "+Invoice+"\n");
        jTextArea1.setText(jTextArea1.getText()+"\nCustomer details:  "+customerdetails+"\n");
        jTextArea1.setText(jTextArea1.getText()+"\nOrder date:  "+date+"\n");
       jTextArea1.setText(jTextArea1.getText()+"\nOrder time:  "+time+"\n");
        jTextArea1.setText(jTextArea1.getText()+"\nQuantity:  "+quantity+"   tray(s)\n");
       jTextArea1.setText(jTextArea1.getText()+"\nPrice:  "+price+"/=\n\n Welcome again..........Thank you");
    
        }
    
    int invoiceId;
    Statement st1=null;
    ResultSet rs1=null;
     private void InvoiceCount(){
    
    try{
    st1=con.createStatement();
    rs1=st1.executeQuery("select MAX( InvoiceId)from Invoice");
    rs1.next();
   invoiceId=rs1.getInt(1)+1;
    
    
    }
    catch(Exception e){
    
    }
     }
     private void IDisplay(){
    
    try{
         Class.forName("org.mariadb.jdbc.Driver");
         Connection con=DriverManager.getConnection("jdbc:mariadb://localhost:3306/brood","root", "Eldinah8703");
         st =con.createStatement();
         rs=st.executeQuery("select*from porders");
         jTable1.setModel(DbUtils.resultSetToTableModel(rs));
        }
        catch(Exception e){
        
        JOptionPane.showMessageDialog(null, e);
        
        }
     
     }
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jtime = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        quantitytbl = new javax.swing.JTextField();
        invoice = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jdate = new javax.swing.JTextField();
        customer = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        price1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Lucida Bright", 1, 14)); // NOI18N
        jTextArea1.setForeground(new java.awt.Color(0, 0, 255));
        jTextArea1.setRows(5);
        jScrollPane2.setViewportView(jTextArea1);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 290, 610, 360));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 620, -1, -1));

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton2.setText("Print receipt");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 650, -1, -1));

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton3.setText("Receipt");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 620, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Order date");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 520, -1, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1290, 280));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("Customer details");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, -1, -1));

        jtime.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jtime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtimeActionPerformed(evt);
            }
        });
        jPanel1.add(jtime, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 520, 150, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("InvoiceId");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 410, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("Order time");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 520, -1, -1));

        quantitytbl.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        quantitytbl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quantitytblActionPerformed(evt);
            }
        });
        jPanel1.add(quantitytbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 410, 70, -1));

        invoice.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        invoice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                invoiceActionPerformed(evt);
            }
        });
        jPanel1.add(invoice, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 410, 100, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setText("Quantity");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 410, -1, -1));

        jdate.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jPanel1.add(jdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 520, 150, -1));

        customer.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jPanel1.add(customer, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 290, 450, 60));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Price");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 410, -1, -1));

        price1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        price1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                price1ActionPerformed(evt);
            }
        });
        jPanel1.add(price1, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 410, 110, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1290, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1290, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 685, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 685, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        processOrder pO=new processOrder();
        pO.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here
        try{
          InvoiceCount();
         Calendar timer=Calendar.getInstance();
        timer.getTime();
        SimpleDateFormat Tt=new SimpleDateFormat("HH:mm:ss");
        jtime.setText(Tt.format(timer.getTime()));
        
         SimpleDateFormat Dd=new SimpleDateFormat("dd-MMM-YYYY");
         jdate.setText(Dd.format(timer.getTime()));
         int quantity=Integer.parseInt(quantitytbl.getText());
        int price;
        price=320*quantity;
        String sub1=String.format("%d/=", price);
        price1.setText(sub1);
       Class.forName("org.mariadb.jdbc.Driver");
       Connection con=DriverManager.getConnection("jdbc:mariadb://localhost:3306/brood","root", "Eldinah8703");
       PreparedStatement Add=con.prepareStatement("insert into  Invoice values (?, ?, ?, ?, ?,?)");
               
                
                Add.setInt(1, Integer.valueOf(invoice.getText()));
                Add.setString(2, customer.getText());
                Add.setString(3, jdate.getText());
                Add.setString(4, jtime.getText());
                Add.setInt(5, Integer.valueOf(quantitytbl.getText()));
               
                 Add.setInt(6,price);
                
                
                 int row=Add.executeUpdate();
                //JOptionPane.showMessageDialog(this, "Order added successfully");
                
                con.close();
               print();
               IDisplay();
                
               } 
       
       catch (Exception e) {
           
            JOptionPane.showMessageDialog(this, "connection error");
        }
       
      
         
       
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
          try{
       
       jTextArea1.print();
       }
       
       catch(Exception e){
       
       
       }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        DefaultTableModel df=(DefaultTableModel)jTable1.getModel();
         int selectedIndex=jTable1.getSelectedRow();
         customer.setText(df.getValueAt(selectedIndex, 1).toString());
         invoice.setText(df.getValueAt(selectedIndex, 0).toString());
         //jtime.setText(df.getValueAt(selectedIndex, 3).toString());
         quantitytbl.setText(df.getValueAt(selectedIndex, 4).toString());
    }//GEN-LAST:event_jTable1MouseClicked

    private void quantitytblActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quantitytblActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_quantitytblActionPerformed

    private void invoiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_invoiceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_invoiceActionPerformed

    private void jtimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtimeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtimeActionPerformed

    private void price1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_price1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_price1ActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Invoice1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Invoice1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Invoice1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Invoice1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Invoice1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField customer;
    private javax.swing.JTextField invoice;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jdate;
    private javax.swing.JTextField jtime;
    private javax.swing.JTextField price1;
    private javax.swing.JTextField quantitytbl;
    // End of variables declaration//GEN-END:variables
}
