/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package e.voting.system;

import java.io.FileInputStream;
import java.io.InputStream;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author ADMIN
 */
public class Voters extends javax.swing.JFrame {

  Connection con=null;
    PreparedStatement pst=null;
    ResultSet rs =null;
    Statement st=null;
    public Voters() {
        initComponents();
       VoterCount();
        VDisplay();
        GetElection();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
     int VId;
    Statement st1=null;
    ResultSet rs1=null;
    private void VoterCount(){
    
    try{
    st1=con.createStatement();
    rs1=st1.executeQuery("select MAX(VId)from voters");
    rs1.next();
    VId=rs1.getInt(1)+1;
    
    
    }
    catch(Exception e){
    }
    }
     private void VDisplay(){
    
    try{
         Class.forName("org.mariadb.jdbc.Driver");
         Connection con=DriverManager.getConnection("jdbc:mariadb://localhost:3306/E_Voting","root", "Eldinah8703");
         st =con.createStatement();
         rs=st.executeQuery("select*from Voters");
         VTable.setModel(DbUtils.resultSetToTableModel(rs));
        }
        catch(Exception e){
        
        JOptionPane.showMessageDialog(null, e);
        
        }
     }
     private void GetElection(){
    
     try{
         Class.forName("org.mariadb.jdbc.Driver");
         Connection con=DriverManager.getConnection("jdbc:mariadb://localhost:3306/E_Voting","root", "Eldinah8703");
         st =con.createStatement();
         rs=st.executeQuery("select*from electiontbl");
        while (rs.next()){
        
            String ElectId=rs.getString("EId");
            VElection.addItem(ElectId);
        
        }
        }
        catch(Exception e){
        
        JOptionPane.showMessageDialog(null, e);
        
        }
     
    
    
     }
     
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        VTable = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        VName = new javax.swing.JTextField();
        VAge = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        VGen = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        VElection = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        VPass = new javax.swing.JPasswordField();
        addbtn = new javax.swing.JButton();
        editbtn = new javax.swing.JButton();
        deletebtn = new javax.swing.JButton();
        backbtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(255, 51, 51));
        jPanel2.setForeground(new java.awt.Color(0, 51, 204));

        jLabel2.setBackground(new java.awt.Color(51, 0, 204));
        jLabel2.setFont(new java.awt.Font("Tahoma", 3, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("E-VOTING  SYSTEM");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 547, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(149, 149, 149))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel1.setBackground(new java.awt.Color(51, 0, 204));
        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 102, 0));
        jLabel1.setText("Manage  voters");

        VTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        VTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                VTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(VTable);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Name");

        VName.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        VAge.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("Age");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("Password");

        VGen.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        VGen.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female", " " }));
        VGen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VGenActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setText("Elections");

        VElection.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        VElection.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                VElectionMouseClicked(evt);
            }
        });
        VElection.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VElectionActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setText("Gender");

        VPass.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        addbtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        addbtn.setText("Add");
        addbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addbtnMouseClicked(evt);
            }
        });
        addbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addbtnActionPerformed(evt);
            }
        });

        editbtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        editbtn.setText("Edit");
        editbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                editbtnMouseClicked(evt);
            }
        });
        editbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editbtnActionPerformed(evt);
            }
        });

        deletebtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        deletebtn.setText("Delete");
        deletebtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                deletebtnMouseClicked(evt);
            }
        });
        deletebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletebtnActionPerformed(evt);
            }
        });

        backbtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        backbtn.setText("Back");
        backbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backbtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(VName, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(jLabel4)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(34, 34, 34)
                                .addComponent(VAge, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(60, 60, 60)
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel8)
                                .addGap(24, 24, 24))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(84, 84, 84)
                        .addComponent(jLabel6))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(VElection, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(99, 99, 99)
                        .addComponent(VPass, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(addbtn)
                        .addGap(28, 28, 28)
                        .addComponent(editbtn)
                        .addGap(26, 26, 26)
                        .addComponent(deletebtn)
                        .addGap(33, 33, 33)
                        .addComponent(backbtn)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 71, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 442, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(301, 301, 301)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(VGen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 379, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(58, 58, 58)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5))
                                .addGap(26, 26, 26))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel8)
                                .addGap(18, 18, 18)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(VGen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(VAge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(VName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(44, 44, 44)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(jLabel6))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(VElection, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(VPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(addbtn)
                            .addComponent(editbtn)
                            .addComponent(deletebtn)
                            .addComponent(backbtn))
                        .addGap(34, 34, 34))))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void VGenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VGenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_VGenActionPerformed

    private void addbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addbtnActionPerformed
        // TODO add your handling code here:
      
    }//GEN-LAST:event_addbtnActionPerformed
    int key=-1;
    private void VTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_VTableMouseClicked
        // TODO add your handling code here:
         DefaultTableModel df=(DefaultTableModel)VTable.getModel();
         int selectedIndex=VTable.getSelectedRow();
         
         key=Integer.valueOf(df.getValueAt(selectedIndex,0).toString());
         VName.setText(df.getValueAt(selectedIndex, 1).toString());
         VAge.setText(df.getValueAt(selectedIndex, 2).toString());
          VPass.setText(df.getValueAt(selectedIndex, 3).toString());
         VGen.setSelectedItem(df.getValueAt(selectedIndex, 4).toString());
         VElection.setSelectedItem(df.getValueAt(selectedIndex, 5).toString());
         
    }//GEN-LAST:event_VTableMouseClicked

    private void deletebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletebtnActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_deletebtnActionPerformed

    private void editbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editbtnActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_editbtnActionPerformed

    private void backbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backbtnActionPerformed

        // TODO add your handling code here:
        new MainDashboard().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backbtnActionPerformed

    private void VElectionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VElectionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_VElectionActionPerformed

    private void VElectionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_VElectionMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_VElectionMouseClicked

    private void addbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addbtnMouseClicked
        String age=VAge.getText();
        
        if(VAge.getText().isEmpty() || VName.getText().isEmpty()||VElection.getSelectedIndex()==-1||VGen.getSelectedIndex()==-1){
        
          JOptionPane.showMessageDialog(this, "missing information");
 
         }
          else if (Integer.parseInt(age)<18){
             
          JOptionPane.showMessageDialog(this, "Below age!!!! Voter not registered");
             
         }
        else{
             
             try {
                 
                 Class.forName("org.mariadb.jdbc.Driver");
                 con=DriverManager.getConnection("jdbc:mariadb://localhost:3306/E_Voting","root", "Eldinah8703");
                 PreparedStatement Add=con.prepareStatement("insert into Voters values (?, ?, ?, ?, ?, ?)");
                 
                 
                 VoterCount();
                 Add.setInt(1, VId);
                 Add.setString(2, VName.getText());
                 Add.setInt(3, Integer.valueOf(VAge.getText()));
                 Add.setString(4, VPass.getText());
                 Add.setString(5, VGen.getSelectedItem().toString());
                 Add.setInt(6, Integer.valueOf(VElection.getSelectedItem().toString()));
                 
                 
                 
                 int row=Add.executeUpdate();
                 JOptionPane.showMessageDialog(this, "Voter registered");
                 VDisplay();
                 con.close();
                 
             } catch (Exception e) {
                 
                 JOptionPane.showMessageDialog(this, e);
                 
             }
             
         }    
    }//GEN-LAST:event_addbtnMouseClicked

    private void deletebtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deletebtnMouseClicked
         
          if (key==-1){
          
          JOptionPane.showMessageDialog(this, "Select voter to be deleted");
          
          } else{
           try{
              
       Class.forName("org.mariadb.jdbc.Driver");
       Connection con=DriverManager.getConnection("jdbc:mariadb://localhost:3306/E_Voting","root", "Eldinah8703");
       String query="delete from Voters where VId="+key;
       Statement del=con.createStatement();
       del.executeUpdate(query);
       JOptionPane.showMessageDialog(this, "Voter deleted successfully");
        VName.setText("   ");
       VAge.setText("   ");
       VGen.setSelectedItem(" ");
       VElection.setSelectedItem(" ");
       VPass.setText("   ");
        VDisplay();  
       
       } 
          
       catch (Exception e) {
           
            JOptionPane.showMessageDialog(this, "connection error");
        }
          }  
       
    }//GEN-LAST:event_deletebtnMouseClicked

    private void editbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editbtnMouseClicked
        if( VAge.getText().isEmpty() || VName.getText().isEmpty()||VElection.getSelectedIndex()==-1||VGen.getSelectedIndex()==-1){
        
     JOptionPane.showMessageDialog(this, "Select voter to be updated");

        }else{
          try{
              
             
       Class.forName("org.mariadb.jdbc.Driver");
       Connection con=DriverManager.getConnection("jdbc:mariadb://localhost:3306/E_Voting","root", "Eldinah8703");
       
        String query="update Voters set VName=?, VAge=?, VPass=?, VGen=?, VElection=? where VId=?";
        PreparedStatement updateQuery=con.prepareStatement(query);
        updateQuery.setString(1, VName.getText());
        updateQuery.setInt(2, Integer.valueOf(VAge.getText().toString()));
        updateQuery.setString(3, VPass.getText());
        updateQuery.setString(4, VGen.getSelectedItem().toString());
        updateQuery.setInt(5, Integer.valueOf(VElection.getSelectedItem().toString()));
         updateQuery.setInt(6, key);

        updateQuery.executeUpdate();
        
       JOptionPane.showMessageDialog(this, " Voters updated successfully");
       VName.setText("   ");
       VAge.setText("   ");
       VPass.setText("   ");
       VGen.setSelectedItem(" ");
       VElection.setSelectedItem(" ");
        VDisplay();
       
     
       
       } 
       
       catch (Exception e) {
           
            JOptionPane.showMessageDialog(this, e);
        }
         
        }
    }//GEN-LAST:event_editbtnMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Voters.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Voters.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Voters.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Voters.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Voters().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField VAge;
    private javax.swing.JComboBox<String> VElection;
    private javax.swing.JComboBox<String> VGen;
    private javax.swing.JTextField VName;
    private javax.swing.JPasswordField VPass;
    private javax.swing.JTable VTable;
    private javax.swing.JButton addbtn;
    private javax.swing.JButton backbtn;
    private javax.swing.JButton deletebtn;
    private javax.swing.JButton editbtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
