/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package e.voting.system;

import java.awt.Image;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author ADMIN
 */
public class Voting extends javax.swing.JFrame {

   Connection con=null;
    PreparedStatement pst=null;
    ResultSet rs =null;
    Statement st=null;
    public Voting() {
        initComponents();
        VotingDisplay();
       
          
        Bravo.setVisible(false);
        
    }
   int VotingId;
    public Voting (int voterId){
         
    initComponents();
        VotingDisplay();
         //VCheck();
      
          
    Bravo.setVisible(false);
    VotingId=voterId;
    
    //JOptionPane.showMessageDialog(this, VotingId);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    int VId;
    Statement st1=null;
    ResultSet rs1=null;
    
    private void votesCount(){
    
    try{
    st1=con.createStatement();
    rs1=st1.executeQuery("select MAX(voteId)from votes");
    rs1.next();
    VId=rs1.getInt(1)+1;
    
    
    }
    catch(Exception e){
    } 
    }
    
   int VNumber;
     private void VCheck(){
    
    try{
     Class.forName("org.mariadb.jdbc.Driver");
     con=DriverManager.getConnection("jdbc:mariadb://localhost:3306/E_Voting","root", "Eldinah8703");
    st1=con.createStatement();
    rs1=st1.executeQuery("select count (*) from votes where voterId='"+VotingId+"' and electId='"+elecId+"' ");
     
     if(rs1.next()){
     
     VNumber=1;
     
     }else{
     
     VNumber=0;
     }
    
    
    } catch(Exception Ex){
        
      JOptionPane.showMessageDialog(this, Ex);  
        
    } 
    
    }
    private void VotingDisplay(){
    
    try{
         Class.forName("org.mariadb.jdbc.Driver");
         Connection con=DriverManager.getConnection("jdbc:mariadb://localhost:3306/E_Voting","root", "Eldinah8703");
         st =con.createStatement();
         rs=st.executeQuery("select*from candidatetbl");
         candidatestbl.setModel(DbUtils.resultSetToTableModel(rs));
        }
        catch(Exception e){
        
        JOptionPane.showMessageDialog(null, e);
        }
        }
    
      private Icon ResizePhoto(String imgpath, byte [] pic){
     
      ImageIcon MyImage=null;
      if (imgpath!=null){
      
      MyImage=new ImageIcon(imgpath);
      
      }else{
      
        MyImage=new ImageIcon(pic);  
      
      }
      Image img =MyImage.getImage();
      Image newImg=img.getScaledInstance(VPhoto.getWidth(),VPhoto.getHeight() , Image.SCALE_SMOOTH);
      ImageIcon image=new ImageIcon(newImg);
      
      return image;
     }
    private void FetchPhoto(){
    
    String query="select CPhoto from candidatetbl  where CId="+key;
    Statement st;
    ResultSet rs;
     try{
     
      Class.forName("org.mariadb.jdbc.Driver");
      con=DriverManager.getConnection("jdbc:mariadb://localhost:3306/E_Voting","root", "Eldinah8703");
       st=con.createStatement();
       rs=st.executeQuery(query);
       if(rs.next()){
       
       VPhoto.setIcon(ResizePhoto(null, rs.getBytes("CPhoto")));
       
       
       }
     }
     catch(Exception e){
     
     
     }
    }
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        VPhoto = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        candidatestbl = new javax.swing.JTable();
        votebtn = new javax.swing.JButton();
        VotingName = new javax.swing.JLabel();
        Bravo = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(255, 51, 51));
        jPanel2.setForeground(new java.awt.Color(0, 51, 204));

        jLabel2.setBackground(new java.awt.Color(51, 0, 204));
        jLabel2.setFont(new java.awt.Font("Tahoma", 3, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("E- VOTING  SYSTEM");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(139, 139, 139)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 547, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 22, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jLabel1.setBackground(new java.awt.Color(51, 0, 204));
        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 102, 0));
        jLabel1.setText("Welcome in mycodespace voting application");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setText("Your candidate");

        VPhoto.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 0, 204));
        jButton1.setText("Back");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        candidatestbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        candidatestbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                candidatestblMouseClicked(evt);
            }
        });
        candidatestbl.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                candidatestblComponentShown(evt);
            }
        });
        jScrollPane1.setViewportView(candidatestbl);

        votebtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        votebtn.setForeground(new java.awt.Color(0, 0, 204));
        votebtn.setText("vote");
        votebtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                votebtnMouseClicked(evt);
            }
        });
        votebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                votebtnActionPerformed(evt);
            }
        });

        VotingName.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        VotingName.setText("Name");

        Bravo.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        Bravo.setForeground(new java.awt.Color(255, 0, 51));
        Bravo.setText("Vote counted!!! Bravo");
        Bravo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BravoMouseClicked(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel11.setText("Candidate list");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane1)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(167, 167, 167)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(VPhoto, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(58, 58, 58)
                                .addComponent(votebtn, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(80, 80, 80)
                                .addComponent(Bravo))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(277, 277, 277)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addComponent(VotingName)))
                .addContainerGap(134, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(358, 358, 358)
                    .addComponent(jLabel11)
                    .addContainerGap(368, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(120, 120, 120)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(votebtn)
                            .addComponent(Bravo)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jLabel7)
                        .addGap(18, 18, 18)
                        .addComponent(VPhoto, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(VotingName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addGap(43, 43, 43))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(420, Short.MAX_VALUE)
                    .addComponent(jLabel11)
                    .addGap(256, 256, 256)))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        new Login().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed
 int key=-1;
 int elecId;
    private void candidatestblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_candidatestblMouseClicked
        // TODO add your handling code here:
        
         DefaultTableModel df=(DefaultTableModel)candidatestbl.getModel();
         int selectedIndex=candidatestbl.getSelectedRow();
         
         key=Integer.valueOf(df.getValueAt(selectedIndex,0).toString());
         VotingName.setText(df.getValueAt(selectedIndex,1).toString());
          elecId=Integer.valueOf(df.getValueAt(selectedIndex,5).toString());
         FetchPhoto();
    }//GEN-LAST:event_candidatestblMouseClicked

    private void candidatestblComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_candidatestblComponentShown
        // TODO add your handling code here:
    }//GEN-LAST:event_candidatestblComponentShown

    private void votebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_votebtnActionPerformed
        // TODO add your handling code here:
       
     
    }//GEN-LAST:event_votebtnActionPerformed

    private void votebtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_votebtnMouseClicked
        // TODO add your handling code here:
        VCheck();
          if(key==-1){
        
            JOptionPane.showMessageDialog(this, "Select your candidate");
        
        }
          else if (VNumber<0){
            
             JOptionPane.showMessageDialog(this, "You can not vote twice!!!!");
        }
          else{
            try{
                votesCount();
            Class.forName("org.mariadb.jdbc.Driver");
          con=DriverManager.getConnection("jdbc:mariadb://localhost:3306/E_Voting","root", "Eldinah8703");
           PreparedStatement Add=con.prepareStatement("insert into votes values (?, ?, ?, ?)");
           
          
       
       Add.setInt(1, VId);
        Add.setInt(2, VotingId);
         Add.setInt(3, elecId);
          Add.setInt(4, key);
       
       
       int row=Add.executeUpdate();
       
       
        JOptionPane.showMessageDialog(this, "vote counted");
         
        
       con.close();
        Bravo.setVisible(true); 
          votebtn.setVisible(false);
      VotingDisplay();
       
            
            }
            catch(Exception e){
            
            JOptionPane.showMessageDialog(this, e);
            
        }
        }
    }//GEN-LAST:event_votebtnMouseClicked

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1MouseClicked

    private void BravoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BravoMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_BravoMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Voting.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Voting.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Voting.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Voting.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Voting().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Bravo;
    private javax.swing.JLabel VPhoto;
    private javax.swing.JLabel VotingName;
    private javax.swing.JTable candidatestbl;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton votebtn;
    // End of variables declaration//GEN-END:variables
}
